name: plan_uek
description: "Aplikacja do planu zajec UEK"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # --- Sieć i HTML ---
  http: ^1.2.0
  html: ^0.15.4
  crypto: ^3.0.3
  
  # --- Formatowanie Dat ---
  intl: ^0.19.0
  
  # --- Bezpieczeństwo ---
  flutter_secure_storage: ^9.0.0
  
  # --- Kalendarz (NOWOŚĆ) ---
  table_calendar: ^3.0.9

  # --- Ikony ---
  cupertino_icons: ^1.0.6

  url_launcher: ^6.2.4
  
  provider: ^6.1.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/UEKlogo.png"
  min_sdk_android: 21